spring.application.name=user-service
server.port=8081

# ========================
# MYSQL CONFIG
# ========================
spring.datasource.url=jdbc:mysql://localhost:3306/microservices_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Pooja
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================
# JPA CONFIG
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ========================
# KAFKA (SAFE MODE - NO ERROR)
# ========================
spring.kafka.listener.missing-topics-fatal=false